<!DOCTYPE html>
<html lang="cs">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link href="styles/header.css" rel="stylesheet">
    <link href="styles/user.css" rel="stylesheet">
    <link href="styles/common.css" rel="stylesheet">
    <link href="styles/footer.css" rel="stylesheet">
    <link href="styles/pokemons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">
    <title>Pokédex</title>
</head>
<body>
<header class="header">
    <div class="header-item">
        <a class="link" href="/">Home</a>
    </div>
    <div class="header-item">
        <a class="link" href="logout">Logout</a>
    </div>
</header>
<div class="content-container">
    <h1 class="title">SPŠE Pokédex - User</h1>
    <form class="filters">
        <div class="filter">
            <label for="order-type">Name:</label>
            <input name="name" type="text" id="order-type" />
        </div>
        <div class="button-container">
            <input type="submit" value="Send" class="submit-button" />
        </div>
    </form>
    <div class="pokemons hover pointer">
        <?php /** @var \App\Entity\Pokemon $pokemon */

        foreach ($pokemons as $pokemon): ?>
            <a href="add-pokemon?id=<?= $pokemon->getId() ?>" class="pokemon">
                <img class="pokemon-image" src="<?= $pokemon->getImageUrl() ?>" alt="Pokémon photo">
                <h3 class="pokemon-number">#<?= $pokemon->getOfficialNumber() ?></h3>
                <h2 class="pokemon-name"><?= $pokemon->getName() ?></h2>
                <div class="skills">
                    <?php /** @var \App\Entity\Type $type */
                    foreach ($pokemon->getTypes() as $type) ?>
                    <div class="skill <?= mb_strtolower($type->getName()) ?>"><?= $type->getName() ?></div>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
</div>
<footer class="footer">
    <h6 class="footer-title">Created by Michal&nbsp;Šmahel & Václav&nbsp;Pavlíček</h6>
</footer>
</body>
</html>