<!DOCTYPE html>
<html lang="cs">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link href="styles/header.css" rel="stylesheet">
    <link href="styles/user.css" rel="stylesheet">
    <link href="styles/common.css" rel="stylesheet">
    <link href="styles/footer.css" rel="stylesheet">
    <link href="styles/pokemons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">
    <title>Pokédex</title>
</head>
<body>
<header class="header">
    <div class="header-item">
        <a class="link" href="/">Home</a>
    </div>
    <div class="header-item">
        <a class="link" href="logout">Logout</a>
    </div>
</header>
<div class="content-container">
    <h1 class="title">SPŠE Pokédex - User</h1>
    <div class="add-pokemon">
        <a class="link" href="select-pokemon">Add pokémon</a>
    </div>
    <form class="filters">
        <div class="filter">
            <label for="pokemon-type">Type:</label>
            <select name="type" id="pokemon-type">
                <option value="">Any</option>
                <?php /** @var \App\Entity\Type $type */

                foreach ($types as $type): ?>
                    <option value="<?= $type->getId() ?>"><?= $type->getName() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <!--<div class="filter">
            <label for="order-type">Order:</label>
            <select id="order-type">
                <option value="alphabetically-ascending">Alphabetically - Ascending</option>
                <option value="alphabetically-descending">Alphabetically - Descending</option>
                <option value="numerically-ascending">Numerically - Ascending</option>
                <option value="numerically-descending">Numerically - Descending</option>
            </select>
        </div>-->
        <div class="button-container">
            <input type="submit" value="Send" class="submit-button" />
        </div>
    </form>
    <div class="pokemons">
        <?php /** @var \App\Entity\Pokemon $pokemon */ foreach ($pokemons as $pokemon): ?>
        <div class="pokemon">
            <div class="header">
                <a href="detail?id=<?= $pokemon->getId() ?>" class="detail-link">
                    <img src="images/info-icon.png" class="icon-image" alt="Info">
                </a>
                <a href="remove?id=<?= $pokemon->getId() ?>" class="delete-button">
                    <img src="images/delete-icon.png" class="icon-image" alt="Delete">
                </a>
            </div>
            <img class="pokemon-image" src="<?= $pokemon->getImageUrl() ?>" alt="Pokémon photo">
            <h3 class="pokemon-number">#<?= $pokemon->getOfficialNumber() ?></h3>
            <h2 class="pokemon-name"><?= $pokemon->getName() ?></h2>
            <div class="skills">
                <?php /** @var \App\Entity\Type $type */

                foreach ($pokemon->getTypes() as $type) ?>
                <div class="skill <?= mb_strtolower($type->getName()) ?>"><?= $type->getName() ?></div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<footer class="footer">
    <h6 class="footer-title">Created by Michal&nbsp;Šmahel & Václav&nbsp;Pavlíček</h6>
</footer>
</body>
</html>