<!DOCTYPE html>
<html lang="cs">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link href="../styles/common.css" rel="stylesheet">
    <link href="../styles/add-user.css" rel="stylesheet">
    <link href="../styles/footer.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">
    <title>Pokédex</title>
</head>
<body>
<div class="content-container">
    <h1 class="title">SPŠE Pokédex - New user</h1>
    <form method="post" class="add-user-form">
        <div class="field-container">
            <label for="login">Username:</label>
            <input name="nick" type="text" id="login" />
        </div>
        <div class="field-container">
            <label for="email">Email:</label>
            <input name="email" type="email" id="email" />
        </div>
        <div class="field-container">
            <label for="password">Password:</label>
            <input name="password" type="password" id="password" />
        </div>
        <div class="field-container">
            <label for="password-again">Password again:</label>
            <input name="password-again" type="password" id="password-again" />
        </div>
        <div class="field-container">
            <label for="first-name">First name:</label>
            <input name="first-name" type="text" id="first-name" />
        </div>
        <div class="field-container">
            <label for="last-name">Last name:</label>
            <input name="last-name" type="text" id="last-name" />
        </div>
        <div class="field-container">
            <label for="birth">Date of birth:</label>
            <input name="birth" type="date" id="birth" />
        </div>
        <div class="button-container">
            <input type="submit" value="Create" class="submit-button" />
        </div>
    </form>
    <?php if (!empty($message)): ?>
        <p><?= $message ?></p>
    <?php endif; ?>
</div>
<footer class="footer">
    <h6 class="footer-title">Created by Michal&nbsp;Šmahel & Václav&nbsp;Pavlíček</h6>
</footer>
</body>
</html>